REPORT_OUTPUT_FOLDER: none
SHOW_ELAPSED_TIME: true

DISABLE_LINTERS:
  - CSS_STYLELINT
  - TYPESCRIPT_STANDARD

COPYPASTE_JSCPD_ARGUMENTS: --threshold 5
HTML_DJLINT_ARGUMENTS: --ignore H030,H031
REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV2_GHA_1
SPELL_FILTER_REGEX_INCLUDE: README.md
