---
name: Linters

on:
    push:

concurrency:
    cancel-in-progress: true
    group: ${{ github.ref }}-${{ github.workflow }}

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: MegaLinter
              uses: oxsecurity/megalinter@e08c2b05e3dbc40af4c23f41172ef1e068a7d651
              id: ml
              env:
                  APPLY_FIXES: all
                  APPLY_FIXES_EVENT: pull_request
                  APPLY_FIXES_MODE: commit
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_ALL_CODEBASE: >-
                      ${{
                        github.event_name == 'push' &&
                        contains(fromJSON('["refs/heads/main"]'), github.ref)
                      }}

            - name: Prepare commit and revert any changes to workflow files
              run: |
                  sudo chown -Rc $UID .git/
                  git checkout -- .github/workflows || true
                  git restore --staged .github/workflows || true

            - name: Commit and push applied linter fixes
              # cspell:ignore stefanzweifel
              uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
              with:
                  commit_message: "fix(mega-linter): apply linters fixes"
                  commit_user_name: megalinter-bot
                  commit_user_email: nicolas.vuillamy@ox.security

            - name: Generate release artefact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
              with:
                  name: New release
                  path: /home/runner/work/website_cv/website_cv
